2022-02-11 10:38:40 - INFO - (MainThread) - app - testing logger
2022-02-11 10:39:31 - INFO - (MainThread) - app - testing logger
2022-02-11 10:50:16 - INFO - (MainThread) - app - testing logger
2022-02-11 10:53:04 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 10:53:04 - INFO - (MainThread) - app - GPIO version: 0.7.1
2022-02-11 10:53:04 - INFO - (MainThread) - app - testing logger
2022-02-11 10:58:16 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 10:58:16 - INFO - (MainThread) - app - GPIO version: 0.7.1
2022-02-11 10:59:25 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 10:59:25 - INFO - (MainThread) - app - GPIO version: 0.7.1
2022-02-11 11:01:09 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 11:01:09 - INFO - (MainThread) - app - GPIO version: 0.7.1
2022-02-11 11:01:38 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 11:01:38 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 11:05:37 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 11:05:37 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 11:05:52 - INFO - (Thread-1) - app - Process URL Request
2022-02-11 11:07:47 - INFO - (Thread-9) - app - Process URL Request
2022-02-11 11:09:12 - INFO - (Thread-17) - app - Process URL Request
2022-02-11 13:14:01 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 13:14:01 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 13:16:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 13:16:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 13:25:16 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 13:25:16 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 13:40:11 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 13:40:11 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 13:40:14 - INFO - (Thread-1) - app - Process URL Request
2022-02-11 13:40:18 - INFO - (Thread-2) - app - Process URL Request
2022-02-11 13:40:20 - INFO - (Thread-3) - app - Process URL Request
2022-02-11 16:09:25 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 16:09:25 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-11 16:17:51 - INFO - (MainThread) - app - RPi version: 3
2022-02-11 16:17:51 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-12 20:18:01 - INFO - (MainThread) - app - RPi version: 3
2022-02-12 20:18:01 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-12 20:18:30 - INFO - (Thread-1) - app - Process URL Request
2022-02-12 20:45:50 - INFO - (Thread-3) - app - Process URL Request
2022-02-12 21:23:53 - INFO - (Thread-7) - app - Process URL Request
2022-02-12 21:25:06 - INFO - (Thread-9) - app - Process URL Request
2022-02-12 21:26:11 - INFO - (Thread-11) - app - Process URL Request
2022-02-12 21:36:58 - INFO - (Thread-15) - app - Process URL Request
2022-02-13 07:13:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-13 07:13:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-14 14:55:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-14 14:55:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-14 14:56:28 - INFO - (Thread-1) - app - Process URL Request
2022-02-14 15:17:30 - INFO - (MainThread) - app - RPi version: 3
2022-02-14 15:17:30 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-14 15:47:14 - INFO - (MainThread) - app - RPi version: 3
2022-02-14 15:47:14 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-14 16:48:52 - INFO - (Thread-2) - app - Process URL Request
2022-02-14 18:41:11 - INFO - (MainThread) - app - RPi version: 3
2022-02-14 18:41:11 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 08:35:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 08:35:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 08:52:12 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 08:52:12 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 09:08:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 09:08:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:37:07 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 15:37:07 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:46:47 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 15:46:47 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:48:11 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 15:48:11 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:48:26 - ERROR - (Thread-1) - app - Exception on /22/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 138, in action
    'modes' : modes
NameError: name 'modes' is not defined
2022-02-15 15:51:38 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 15:51:38 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:51:45 - ERROR - (Thread-1) - app - Exception on /22/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 142, in action
    return render_template('main.html', **templateData)
NameError: name 'templateData' is not defined
2022-02-15 15:52:57 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 15:52:57 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:53:03 - ERROR - (Thread-1) - app - Exception on /22/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 142, in action
    return render_template('main.html', **templateData)
NameError: name 'templateData' is not defined
2022-02-15 15:54:19 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 15:54:19 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 15:54:25 - ERROR - (Thread-1) - app - Exception on /22/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'action' did not return a valid response. The function either returned None or ended without a return statement.
2022-02-15 16:01:42 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:01:42 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:01:51 - ERROR - (Thread-1) - app - Exception on /22/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 142, in action
    return render_template('main.html', **templateData)
NameError: name 'templateData' is not defined
2022-02-15 16:04:05 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:04:05 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:04:12 - ERROR - (Thread-1) - app - Exception on /22/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 142, in action
    return render_template('main.html', **templateData)
NameError: name 'templateData' is not defined
2022-02-15 16:05:31 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:05:31 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:10:29 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:10:29 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:23:48 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:23:48 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:23:48 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 16:28:26 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:28:26 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:28:26 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 16:33:34 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:33:34 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:33:34 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 16:38:28 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:38:28 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:38:28 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 16:59:46 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 16:59:46 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 16:59:46 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 18:15:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:15:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:15:54 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 18:27:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:27:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:27:10 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 18:28:41 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:28:41 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:28:41 - INFO - (TrafficLightControllerThread) - TrafficLightController - TrafficLightController started...
2022-02-15 18:32:40 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:32:40 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:41:18 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:41:18 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:47:36 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:47:36 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:47:51 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:47:51 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-15 18:48:24 - INFO - (MainThread) - app - RPi version: 3
2022-02-15 18:48:24 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 08:38:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 08:38:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 08:39:48 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 08:39:48 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 08:42:02 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 08:42:02 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 08:42:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 08:42:59 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 09:53:17 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 09:53:17 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 09:53:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 09:53:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 09:55:04 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 09:55:04 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:00:38 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:00:38 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:00:51 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:00:51 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:01:14 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:01:14 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:27:18 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:27:18 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:27:31 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:27:31 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:39:23 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:39:23 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:55:11 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:55:11 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 10:57:00 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 10:57:00 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:41:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:41:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:43:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:43:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:44:03 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:44:03 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:44:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:44:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:45:46 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:45:46 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:46:07 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:46:07 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:47:22 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:47:22 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:47:25 - INFO - (MainThread) - app - signal SIGINT received by process with PID 4268
2022-02-16 13:47:25 - INFO - (MainThread) - app - Terminating program...
2022-02-16 13:47:25 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 13:47:26 - INFO - (MainThread) - app - Done!
2022-02-16 13:48:55 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:48:55 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 13:49:00 - INFO - (MainThread) - app - signal SIGINT received by process with PID 4277
2022-02-16 13:49:00 - INFO - (MainThread) - app - Terminating program...
2022-02-16 13:49:00 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 13:49:01 - INFO - (MainThread) - app - Done!
2022-02-16 13:49:49 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 13:49:49 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:29:48 - INFO - (MainThread) - app - signal SIGINT received by process with PID 4282
2022-02-16 14:29:48 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:29:48 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:29:49 - INFO - (MainThread) - app - Done!
2022-02-16 14:30:03 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:30:03 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:30:27 - INFO - (MainThread) - app - signal SIGINT received by process with PID 5816
2022-02-16 14:30:27 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:30:27 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:30:28 - INFO - (MainThread) - app - Done!
2022-02-16 14:30:38 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:30:38 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:30:39 - INFO - (MainThread) - app - signal SIGINT received by process with PID 5830
2022-02-16 14:30:39 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:30:39 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:30:40 - INFO - (MainThread) - app - Done!
2022-02-16 14:31:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:31:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:32:09 - INFO - (MainThread) - app - signal SIGINT received by process with PID 5836
2022-02-16 14:32:09 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:32:09 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:32:10 - INFO - (MainThread) - app - Done!
2022-02-16 14:32:49 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:32:49 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:32:51 - INFO - (MainThread) - app - signal SIGINT received by process with PID 5852
2022-02-16 14:32:51 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:32:51 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:32:52 - INFO - (MainThread) - app - Done!
2022-02-16 14:54:19 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:54:19 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:54:59 - INFO - (MainThread) - app - signal SIGINT received by process with PID 9478
2022-02-16 14:54:59 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:54:59 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:55:00 - INFO - (MainThread) - app - Done!
2022-02-16 14:55:17 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:55:17 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:55:20 - INFO - (MainThread) - app - signal SIGINT received by process with PID 9636
2022-02-16 14:55:20 - INFO - (MainThread) - app - Terminating program...
2022-02-16 14:55:20 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 14:55:21 - INFO - (MainThread) - app - Done!
2022-02-16 14:59:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 14:59:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 14:59:30 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 14:59:35 - ERROR - (Thread-2) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 14:59:36 - ERROR - (Thread-3) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:00:01 - INFO - (MainThread) - app - signal SIGINT received by process with PID 10669
2022-02-16 15:00:01 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:00:01 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:00:02 - INFO - (MainThread) - app - Done!
2022-02-16 15:00:52 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:00:52 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:00:56 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:01:03 - ERROR - (Thread-2) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:01:05 - ERROR - (Thread-3) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:01:28 - INFO - (MainThread) - app - signal SIGINT received by process with PID 10680
2022-02-16 15:01:28 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:01:28 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:01:29 - INFO - (MainThread) - app - Done!
2022-02-16 15:01:37 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:01:37 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:01:46 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:01:53 - ERROR - (Thread-2) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:01:54 - ERROR - (Thread-3) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 194, in action
    return render_template('main.html', **templateData)
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 16, in top-level template code
    {% if servos[pin].state == true %}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-16 15:09:48 - INFO - (MainThread) - app - signal SIGINT received by process with PID 10817
2022-02-16 15:09:48 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:09:48 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:09:49 - INFO - (MainThread) - app - Done!
2022-02-16 15:09:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:09:59 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:10:19 - INFO - (MainThread) - app - signal SIGINT received by process with PID 11610
2022-02-16 15:10:19 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:10:19 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:10:20 - INFO - (MainThread) - app - Done!
2022-02-16 15:10:30 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:10:30 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:10:34 - INFO - (MainThread) - app - signal SIGINT received by process with PID 11613
2022-02-16 15:10:34 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:10:34 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:10:35 - INFO - (MainThread) - app - Done!
2022-02-16 15:24:42 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:24:42 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:27:45 - INFO - (MainThread) - app - signal SIGINT received by process with PID 12643
2022-02-16 15:27:45 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:27:45 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:27:46 - INFO - (MainThread) - app - Done!
2022-02-16 15:27:56 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:27:56 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:29:15 - INFO - (MainThread) - app - signal SIGINT received by process with PID 12825
2022-02-16 15:29:15 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:29:15 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:29:16 - INFO - (MainThread) - app - Done!
2022-02-16 15:29:31 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:29:31 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:32:17 - INFO - (MainThread) - app - signal SIGINT received by process with PID 13183
2022-02-16 15:32:17 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:32:17 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:32:18 - INFO - (MainThread) - app - Done!
2022-02-16 15:32:41 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:32:41 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:42:12 - INFO - (MainThread) - app - signal SIGINT received by process with PID 13432
2022-02-16 15:42:12 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:42:12 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:42:13 - INFO - (MainThread) - app - Done!
2022-02-16 15:42:24 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:42:24 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:42:58 - INFO - (MainThread) - app - signal SIGINT received by process with PID 13975
2022-02-16 15:42:58 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:42:58 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:42:59 - INFO - (MainThread) - app - Done!
2022-02-16 15:43:55 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:43:55 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:46:35 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14057
2022-02-16 15:46:35 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:46:35 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:46:36 - INFO - (MainThread) - app - Done!
2022-02-16 15:46:46 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:46:46 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:48:43 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14469
2022-02-16 15:48:43 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:48:43 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:48:44 - INFO - (MainThread) - app - Done!
2022-02-16 15:48:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:48:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:52:06 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14541
2022-02-16 15:52:06 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:52:06 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:52:07 - INFO - (MainThread) - app - Done!
2022-02-16 15:52:16 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:52:16 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:52:21 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14656
2022-02-16 15:52:21 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:52:21 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:52:22 - INFO - (MainThread) - app - Done!
2022-02-16 15:52:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:52:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:53:00 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 15:53:36 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14761
2022-02-16 15:53:36 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:53:36 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:53:37 - INFO - (MainThread) - app - Done!
2022-02-16 15:53:46 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:53:46 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:53:52 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 15:54:16 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14850
2022-02-16 15:54:16 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:54:16 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:54:17 - INFO - (MainThread) - app - Done!
2022-02-16 15:54:33 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:54:33 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:54:55 - INFO - (MainThread) - app - signal SIGINT received by process with PID 14856
2022-02-16 15:54:55 - INFO - (MainThread) - app - Terminating program...
2022-02-16 15:54:55 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 15:54:56 - INFO - (MainThread) - app - Done!
2022-02-16 15:56:05 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 15:56:05 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 15:56:10 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2022-02-16 16:02:06 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:02:06 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:02:11 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:02:16 - ERROR - (Thread-3) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:02:18 - ERROR - (Thread-4) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:03:17 - INFO - (MainThread) - app - signal SIGINT received by process with PID 2578
2022-02-16 16:03:17 - INFO - (MainThread) - app - Terminating program...
2022-02-16 16:03:17 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 16:03:18 - INFO - (MainThread) - app - Done!
2022-02-16 16:03:28 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:03:28 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:03:34 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:03:36 - ERROR - (Thread-2) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:04:21 - ERROR - (Thread-3) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:06:59 - INFO - (MainThread) - app - signal SIGINT received by process with PID 2628
2022-02-16 16:06:59 - INFO - (MainThread) - app - Terminating program...
2022-02-16 16:06:59 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 16:07:00 - INFO - (MainThread) - app - Done!
2022-02-16 16:07:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:07:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:07:14 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:07:17 - ERROR - (Thread-2) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:09:11 - INFO - (MainThread) - app - signal SIGINT received by process with PID 2714
2022-02-16 16:09:11 - INFO - (MainThread) - app - Terminating program...
2022-02-16 16:09:11 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-16 16:09:12 - INFO - (MainThread) - app - Done!
2022-02-16 16:09:21 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:09:21 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:09:26 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:09:28 - ERROR - (Thread-2) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:09:30 - ERROR - (Thread-3) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:31:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:31:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:31:13 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:32:36 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:32:36 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:33:07 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:35:55 - ERROR - (Thread-3) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:35:58 - ERROR - (Thread-4) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:36:04 - ERROR - (Thread-5) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:36:06 - ERROR - (Thread-6) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:36:07 - ERROR - (Thread-7) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:36:08 - ERROR - (Thread-8) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:36:09 - ERROR - (Thread-9) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:38:02 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:38:02 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:38:12 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 173, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:45:38 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:45:38 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:45:46 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 174, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:46:42 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:46:42 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:48:13 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:48:13 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:48:19 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-16 16:48:19 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 175, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 16:59:29 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 16:59:29 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 16:59:36 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-16 16:59:36 - ERROR - (Thread-1) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 175, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 17:00:24 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-16 17:00:24 - ERROR - (Thread-2) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 175, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 17:00:26 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-16 17:00:26 - ERROR - (Thread-3) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 175, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 17:00:28 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-16 17:00:28 - ERROR - (Thread-4) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 175, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 17:00:29 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-16 17:00:29 - ERROR - (Thread-5) - app - Exception on /0/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 175, in action
    GPIO.output(changePin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
2022-02-16 17:03:20 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 17:03:20 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 17:03:24 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-16 17:03:36 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-16 17:03:39 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-16 17:03:41 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-16 17:03:43 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-16 17:03:45 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-16 17:03:48 - INFO - (Thread-7) - app - Dosao ovde!!!
2022-02-16 17:03:50 - INFO - (Thread-8) - app - Dosao ovde!!!
2022-02-16 17:03:51 - INFO - (Thread-9) - app - Dosao ovde!!!
2022-02-16 17:05:21 - INFO - (MainThread) - app - RPi version: 3
2022-02-16 17:05:21 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-16 17:05:27 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-16 17:05:31 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-16 17:05:34 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-16 17:05:51 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 08:55:24 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 08:55:24 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 08:55:33 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 08:55:37 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 08:55:39 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-17 08:55:40 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 08:55:41 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 08:55:42 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-17 08:55:43 - INFO - (Thread-7) - app - Dosao ovde!!!
2022-02-17 08:55:43 - INFO - (Thread-8) - app - Dosao ovde!!!
2022-02-17 08:55:44 - INFO - (Thread-9) - app - Dosao ovde!!!
2022-02-17 08:55:44 - INFO - (Thread-10) - app - Dosao ovde!!!
2022-02-17 08:55:44 - INFO - (Thread-11) - app - Dosao ovde!!!
2022-02-17 08:55:44 - INFO - (Thread-12) - app - Dosao ovde!!!
2022-02-17 08:55:46 - INFO - (Thread-13) - app - Dosao ovde!!!
2022-02-17 08:55:48 - INFO - (Thread-14) - app - Dosao ovde!!!
2022-02-17 08:55:49 - INFO - (Thread-15) - app - Dosao ovde!!!
2022-02-17 08:56:07 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 08:56:07 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 08:56:12 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 08:58:06 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 08:58:06 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 08:58:25 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 08:58:25 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 08:58:30 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 08:58:31 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 09:01:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:01:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:01:48 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 09:01:51 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 09:01:52 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-17 09:01:53 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 09:01:54 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 09:01:55 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-17 09:02:15 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:02:15 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:06:37 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:06:37 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:06:42 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 09:07:37 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:07:37 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:09:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:09:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:09:17 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 09:09:22 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 09:09:24 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-17 09:09:26 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 09:09:28 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 09:09:29 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-17 09:09:31 - INFO - (Thread-7) - app - Dosao ovde!!!
2022-02-17 09:10:37 - INFO - (Thread-8) - app - Dosao ovde!!!
2022-02-17 09:10:41 - INFO - (Thread-9) - app - Dosao ovde!!!
2022-02-17 09:10:42 - INFO - (Thread-10) - app - Dosao ovde!!!
2022-02-17 09:10:44 - INFO - (Thread-11) - app - Dosao ovde!!!
2022-02-17 09:10:46 - INFO - (Thread-12) - app - Dosao ovde!!!
2022-02-17 09:10:47 - INFO - (Thread-13) - app - Dosao ovde!!!
2022-02-17 09:10:55 - INFO - (Thread-14) - app - Dosao ovde!!!
2022-02-17 09:10:56 - INFO - (Thread-15) - app - Dosao ovde!!!
2022-02-17 09:10:58 - INFO - (Thread-16) - app - Dosao ovde!!!
2022-02-17 09:10:59 - INFO - (Thread-17) - app - Dosao ovde!!!
2022-02-17 09:11:00 - INFO - (Thread-18) - app - Dosao ovde!!!
2022-02-17 09:11:01 - INFO - (Thread-19) - app - Dosao ovde!!!
2022-02-17 09:11:03 - INFO - (Thread-20) - app - Dosao ovde!!!
2022-02-17 09:11:04 - INFO - (Thread-21) - app - Dosao ovde!!!
2022-02-17 09:11:07 - INFO - (Thread-22) - app - Dosao ovde!!!
2022-02-17 09:11:08 - INFO - (Thread-23) - app - Dosao ovde!!!
2022-02-17 09:12:20 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:12:20 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:12:24 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 09:12:26 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 09:12:41 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:12:41 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:12:55 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 09:12:58 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 09:13:01 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 09:13:03 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-17 09:13:07 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 09:13:10 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-17 09:13:14 - INFO - (Thread-7) - app - Dosao ovde!!!
2022-02-17 09:13:15 - INFO - (Thread-8) - app - Dosao ovde!!!
2022-02-17 09:33:29 - INFO - (Thread-9) - app - Dosao ovde!!!
2022-02-17 09:33:31 - INFO - (Thread-10) - app - Dosao ovde!!!
2022-02-17 09:33:32 - INFO - (Thread-11) - app - Dosao ovde!!!
2022-02-17 09:33:33 - INFO - (Thread-12) - app - Dosao ovde!!!
2022-02-17 09:41:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:41:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 09:41:33 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 09:41:37 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 09:42:25 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 09:42:26 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 09:42:27 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-17 09:42:29 - INFO - (Thread-7) - app - Dosao ovde!!!
2022-02-17 09:42:30 - INFO - (Thread-8) - app - Dosao ovde!!!
2022-02-17 09:42:31 - INFO - (Thread-9) - app - Dosao ovde!!!
2022-02-17 09:42:32 - INFO - (Thread-10) - app - Dosao ovde!!!
2022-02-17 09:42:33 - INFO - (Thread-11) - app - Dosao ovde!!!
2022-02-17 09:42:58 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 09:42:58 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:13:20 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:13:20 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:13:43 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 10:13:46 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 10:14:09 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:14:09 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:14:22 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 10:14:24 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 10:14:26 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-17 10:14:28 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 10:15:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:15:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:15:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:15:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:22:22 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:22:22 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:22:32 - INFO - (Thread-1) - app - Dosao ovde!!!
2022-02-17 10:22:33 - INFO - (Thread-2) - app - Dosao ovde!!!
2022-02-17 10:22:34 - INFO - (Thread-3) - app - Dosao ovde!!!
2022-02-17 10:22:35 - INFO - (Thread-4) - app - Dosao ovde!!!
2022-02-17 10:22:37 - INFO - (Thread-5) - app - Dosao ovde!!!
2022-02-17 10:22:37 - INFO - (Thread-6) - app - Dosao ovde!!!
2022-02-17 10:23:09 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:23:09 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:25:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:25:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:44:35 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:44:35 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:45:02 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:45:02 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:50:37 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:50:37 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:51:07 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:51:07 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 10:57:31 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 10:57:31 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:00:25 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:00:25 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:00:41 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:00:41 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:13:05 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:13:05 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:49:58 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:49:58 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:50:49 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:50:49 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:53:30 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:53:30 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:53:50 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:53:50 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:53:54 - ERROR - (Thread-1) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 208, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 34, in template
    {% endfor %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2022-02-17 11:54:14 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:54:15 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 11:55:50 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 11:55:50 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 14:26:38 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 14:26:38 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:14:20 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:14:20 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:30:50 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:30:50 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:31:12 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:31:12 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:36:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:36:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:37:22 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:37:22 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:56:53 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:56:53 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 16:58:04 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 16:58:04 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 17:31:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 17:31:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 17:31:49 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 17:31:49 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-17 17:32:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-17 17:32:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:34:23 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:34:23 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:35:40 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:35:40 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:45:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:45:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:46:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:46:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:55:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:55:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:55:32 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 208, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 26, in top-level template code
    <h2>{{ servos[0].name }}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-18 08:55:57 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:55:57 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:57:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:57:59 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 08:58:05 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 208, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 26, in top-level template code
    <h2>{{ servos[0].name }}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-18 08:58:09 - ERROR - (Thread-2) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 208, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 26, in top-level template code
    <h2>{{ servos[0].name }}
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'servos' is undefined
2022-02-18 08:58:44 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 08:58:44 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:00:56 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:00:56 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:02:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:02:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:03:17 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:03:17 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:04:47 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:04:47 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:06:07 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:06:07 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:06:55 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:06:55 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:12:15 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:12:15 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:13:40 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:13:40 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:17:47 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:17:47 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:20:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:20:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:22:01 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:22:01 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:23:21 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:23:21 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:23:24 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 207, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 27, in template
    {% for for pin in pins  %}
jinja2.exceptions.TemplateSyntaxError: expected token 'in', got 'pin'
2022-02-18 09:24:03 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:24:03 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:24:21 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 207, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 27, in template
    {% for for pin in pins %}
jinja2.exceptions.TemplateSyntaxError: expected token 'in', got 'pin'
2022-02-18 09:25:30 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:25:30 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:26:50 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:26:50 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:38:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:38:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 09:55:26 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 09:55:26 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:03:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:03:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:04:33 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:04:33 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:06:34 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:06:34 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:07:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:07:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:09:24 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:09:24 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:14:13 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:14:13 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:42:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:42:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:42:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:42:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:47:51 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:47:51 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:48:34 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:48:34 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:49:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:49:59 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 10:52:42 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 10:52:42 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 14:18:13 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 14:18:13 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-18 14:18:18 - INFO - (Thread-1) - app - Process URL Request
2022-02-18 20:05:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-18 20:05:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
                                                                                                                                       2022-02-21 11:06:16 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:06:16 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:06:22 - INFO - (Thread-2) - app - Process URL Request
2022-02-21 11:09:02 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:09:02 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:09:12 - ERROR - (Thread-5) - app - Exception on /mode/2-Way Stop Mode/on/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 228, in mode
    sendQueue.put('StopAlltemplateDataModes')
NameError: name 'sendQueue' is not defined
2022-02-21 11:15:22 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:15:22 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:15:55 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:15:55 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:19:19 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:19:19 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:19:24 - ERROR - (Thread-1) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 185, in action
    print(servo)
NameError: name 'servo' is not defined
2022-02-21 11:19:35 - ERROR - (Thread-2) - app - Exception on /22/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 185, in action
    print(servo)
NameError: name 'servo' is not defined
2022-02-21 11:27:33 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:27:33 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:40:36 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:40:36 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:41:23 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:41:23 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:57:20 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:57:20 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 11:59:33 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 11:59:33 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 13:42:35 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 13:42:35 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 13:42:46 - ERROR - (Thread-1) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos['name']
KeyError: 'name'
2022-02-21 13:42:50 - ERROR - (Thread-2) - app - Exception on /22/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos['name']
KeyError: 'name'
2022-02-21 13:42:58 - ERROR - (Thread-3) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos['name']
KeyError: 'name'
2022-02-21 13:44:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 13:44:59 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 13:45:05 - ERROR - (Thread-1) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:45:09 - ERROR - (Thread-2) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:45:10 - ERROR - (Thread-3) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:45:45 - INFO - (Thread-5) - app - Process URL Request
2022-02-21 13:45:52 - ERROR - (Thread-7) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 13:45:58 - ERROR - (Thread-8) - app - Exception on /22/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 22
2022-02-21 13:46:23 - ERROR - (Thread-11) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:46:27 - ERROR - (Thread-10) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:50:04 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 13:50:04 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 13:50:14 - ERROR - (Thread-2) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:50:29 - ERROR - (Thread-1) - app - Exception on /23/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:50:57 - INFO - (Thread-4) - app - Process URL Request
2022-02-21 13:51:02 - ERROR - (Thread-6) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 13:51:08 - ERROR - (Thread-7) - app - Exception on /22/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 22
2022-02-21 13:51:15 - ERROR - (Thread-8) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 13:51:24 - ERROR - (Thread-9) - app - Exception on /23/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 23
2022-02-21 13:56:30 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 13:56:30 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 14:04:24 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 14:04:24 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 14:04:31 - INFO - (Thread-1) - app - Process URL Request
2022-02-21 14:04:33 - ERROR - (Thread-2) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 14:04:41 - ERROR - (Thread-3) - app - Exception on /22/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 22
2022-02-21 14:11:03 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 14:11:03 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 14:11:08 - ERROR - (Thread-1) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 14:14:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 14:14:59 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 14:15:11 - ERROR - (Thread-1) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 14:15:19 - ERROR - (Thread-2) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 27
2022-02-21 14:15:23 - ERROR - (Thread-3) - app - Exception on /22/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 180, in action
    deviceName = servos[changePin]['name']
KeyError: 22
2022-02-21 14:21:43 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 14:21:43 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-21 14:22:08 - INFO - (MainThread) - app - RPi version: 3
2022-02-21 14:22:08 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-22 17:46:11 - INFO - (MainThread) - app - RPi version: 3
2022-02-22 17:46:11 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-22 17:49:09 - INFO - (MainThread) - app - RPi version: 3
2022-02-22 17:49:09 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-22 17:49:23 - INFO - (Thread-1) - app - Process URL Request
2022-02-22 17:52:23 - INFO - (MainThread) - app - RPi version: 3
2022-02-22 17:52:23 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-22 17:55:57 - INFO - (MainThread) - app - RPi version: 3
2022-02-22 17:55:57 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 09:49:10 - INFO - (MainThread) - app - RPi version: 3
2022-02-23 09:49:10 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 09:56:23 - INFO - (MainThread) - app - RPi version: 3
2022-02-23 09:56:23 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 09:56:44 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-23 09:56:45 - INFO - (MainThread) - app - Done!
2022-02-23 10:05:11 - INFO - (MainThread) - app - RPi version: 3
2022-02-23 10:05:11 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 10:05:18 - ERROR - (Thread-1) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 199, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 15, in template
    <h2>{{ pins[pin].name servos[servo].name}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'servos'
2022-02-23 10:05:22 - ERROR - (Thread-2) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 199, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 15, in template
    <h2>{{ pins[pin].name servos[servo].name}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'servos'
2022-02-23 10:05:26 - ERROR - (Thread-4) - app - Exception on /27/on [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 199, in action
    return render_template('main.html', **templateData )
  File "/usr/local/lib/python3.9/dist-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dm/clawproject/templates/main.html", line 15, in template
    <h2>{{ pins[pin].name servos[servo].name}}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'servos'
2022-02-23 10:05:37 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-23 10:05:38 - INFO - (MainThread) - app - Done!
2022-02-23 10:06:08 - INFO - (MainThread) - app - RPi version: 3
2022-02-23 10:06:08 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 15:56:04 - INFO - (Thread-3) - app - Process URL Request
2022-02-23 16:24:33 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-23 16:24:34 - INFO - (MainThread) - app - Done!
2022-02-23 16:24:47 - INFO - (MainThread) - app - RPi version: 3
2022-02-23 16:24:47 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 16:33:58 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-23 16:33:59 - INFO - (MainThread) - app - Done!
2022-02-23 16:39:54 - INFO - (MainThread) - app - RPi version: 3
2022-02-23 16:39:54 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-23 16:59:51 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-23 16:59:52 - INFO - (MainThread) - app - Done!
2022-02-24 08:36:36 - INFO - (MainThread) - app - RPi version: 3
2022-02-24 08:36:36 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-24 09:06:15 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-24 09:06:16 - INFO - (MainThread) - app - Done!
2022-02-24 09:09:53 - INFO - (MainThread) - app - RPi version: 3
2022-02-24 09:09:53 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-24 09:10:42 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-24 09:10:43 - INFO - (MainThread) - app - Done!
2022-02-24 10:03:30 - INFO - (MainThread) - app - RPi version: 3
2022-02-24 10:03:30 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-24 11:15:32 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-24 11:15:33 - INFO - (MainThread) - app - Done!
2022-02-25 14:23:49 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:23:49 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:28:16 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 14:28:17 - INFO - (MainThread) - app - Done!
2022-02-25 14:28:27 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:28:27 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:37:17 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 14:37:18 - INFO - (MainThread) - app - Done!
2022-02-25 14:37:26 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:37:26 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:39:24 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 14:39:25 - INFO - (MainThread) - app - Done!
2022-02-25 14:39:32 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:39:32 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:42:07 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 14:42:08 - INFO - (MainThread) - app - Done!
2022-02-25 14:42:16 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:42:16 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:43:40 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 14:43:41 - INFO - (MainThread) - app - Done!
2022-02-25 14:43:49 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:43:49 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:51:39 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 14:51:40 - INFO - (MainThread) - app - Done!
2022-02-25 14:51:47 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:51:47 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:54:14 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:54:14 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:55:40 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:55:40 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 14:58:59 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 14:59:00 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 15:14:53 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 15:14:53 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 15:21:13 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 15:21:13 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 15:21:21 - ERROR - (Thread-1) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 171, in action
    tst = request.form[timerBTN].value + 1
NameError: name 'timerBTN' is not defined
2022-02-25 15:21:24 - ERROR - (Thread-2) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 171, in action
    tst = request.form[timerBTN].value + 1
NameError: name 'timerBTN' is not defined
2022-02-25 15:21:25 - ERROR - (Thread-3) - app - Exception on /27/off [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dm/clawproject/app.py", line 171, in action
    tst = request.form[timerBTN].value + 1
NameError: name 'timerBTN' is not defined
2022-02-25 15:21:52 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 15:21:53 - INFO - (MainThread) - app - Done!
2022-02-25 15:22:02 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 15:22:02 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 15:22:39 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 15:22:40 - INFO - (MainThread) - app - Done!
2022-02-25 15:22:47 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 15:22:47 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-02-25 15:26:33 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-02-25 15:26:34 - INFO - (MainThread) - app - Done!
2022-02-25 15:29:33 - INFO - (MainThread) - app - RPi version: 3
2022-02-25 15:29:33 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-03-01 15:22:42 - INFO - (MainThread) - app - RPi version: 3
2022-03-01 15:22:42 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-03-01 15:25:51 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-03-01 15:25:52 - INFO - (MainThread) - app - Done!
2022-03-01 15:26:02 - INFO - (MainThread) - app - RPi version: 3
2022-03-01 15:26:02 - INFO - (MainThread) - app - GPIO version: 0.7.0
2022-03-01 16:13:20 - INFO - (MainThread) - app - Cleaning up GPIO...
2022-03-01 16:13:21 - INFO - (MainThread) - app - Done!
